### PR TITLE
Changed for loops to each loop

### PR DESCRIPTION
**Pull request by arian-amador**
Check this article for a quick write up on for loops in Ruby: [The Evils of the For Loop](http://graysoftinc.com/early-steps/the-evils-of-the-for-loop)

Something I noticed while go over the code and figured I'd see what you thought.

### CODE REVIEW

**Comment by arian-amador** [comment]
Looks like it included the other commits also...

**Comment by JVillella** [comment]
I didn't know this subtle behaviour about the for in! Thanks for sharing. I'm happy to change it to the `each`. Small suggestion, what if we write the loops like this:

```
(0...height).each do |y|
```

Note: the **3 dot** syntax excludes the end range value.

Instead of

```
(height - 1).times.each do |y|
```

The `times` shouldn't be necessary. I imagine it actually creates an additional loop to achieve this behaviour.

**Comment by arian-amador** [comment]
Great suggestion. The '...' notation is perfect for that.

**Comment by JVillella** [comment]
That looks great! If you just want to rebase against current master and apply the one commit with the loop improvements I will merge it in. (if it's easier feel free to do it as another PR and close this one, or just force push here).

**Comment by JVillella** [comment]
Awesome!

**Pull request merged**
